/**
 * POST /tools/weather_get_current
 *
 * Get current public weather for a city name.
 *
 * Generated by @orchet/agent-cli. Edit the body to plug in vendor-
 * specific request shaping or error handling — the boilerplate
 * (bearer extraction, Zod parsing, error envelope) is stable and
 * matches what the orchestrator expects.
 */
import { type NextRequest, NextResponse } from "next/server";
import { z } from "zod";

export const runtime = "edge";
export const dynamic = "force-dynamic";

// Request schema (generated from OpenAPI / docs spec).
const Body = z.object({
  city: z.string().min(1),
  units: z.enum(["metric", "imperial"]).default("metric"),
});

export async function POST(req: NextRequest) {


  let body: z.infer<typeof Body>;
  try {
    body = Body.parse(await req.json().catch(() => ({})));
  } catch (err) {
    return NextResponse.json(
      { error: "invalid_body", detail: err instanceof Error ? err.message : String(err) },
      { status: 400 },
    );
  }

  try {
    const city = body.city.trim();
    const units = body.units;

    const geoUrl = new URL("https://geocoding-api.open-meteo.com/v1/search");
    geoUrl.searchParams.set("name", city);
    geoUrl.searchParams.set("count", "1");
    geoUrl.searchParams.set("language", "en");
    geoUrl.searchParams.set("format", "json");
    const geoRes = await fetch(geoUrl, { headers: { accept: "application/json" } });
    if (!geoRes.ok) {
      return NextResponse.json({ error: { code: "provider_error", message: `Open-Meteo geocoding returned ${geoRes.status}` } }, { status: 502 });
    }
    const geo = await geoRes.json() as { results?: Array<{ name: string; country?: string; latitude: number; longitude: number }> };
    const place = geo.results?.[0];
    if (!place) {
      return NextResponse.json({ error: { code: "not_found", message: `No weather location found for ${city}` } }, { status: 404 });
    }

    const weatherUrl = new URL("https://api.open-meteo.com/v1/forecast");
    weatherUrl.searchParams.set("latitude", String(place.latitude));
    weatherUrl.searchParams.set("longitude", String(place.longitude));
    weatherUrl.searchParams.set("current", "temperature_2m,wind_speed_10m");
    if (units === "imperial") {
      weatherUrl.searchParams.set("temperature_unit", "fahrenheit");
      weatherUrl.searchParams.set("wind_speed_unit", "mph");
    }
    const weatherRes = await fetch(weatherUrl, { headers: { accept: "application/json" } });
    if (!weatherRes.ok) {
      return NextResponse.json({ error: { code: "provider_error", message: `Open-Meteo weather returned ${weatherRes.status}` } }, { status: 502 });
    }
    const weather = await weatherRes.json() as {
      current?: { temperature_2m?: number; wind_speed_10m?: number };
      current_units?: { temperature_2m?: string; wind_speed_10m?: string };
    };
    const locationLabel = place.country ? `${place.name}, ${place.country}` : place.name;
    const temperature = Number(weather.current?.temperature_2m ?? 0);
    const windSpeed = Number(weather.current?.wind_speed_10m ?? 0);
    const temperatureUnit = weather.current_units?.temperature_2m ?? (units === "imperial" ? "°F" : "°C");
    const windSpeedUnit = weather.current_units?.wind_speed_10m ?? (units === "imperial" ? "mph" : "km/h");
    return NextResponse.json({
      city: locationLabel,
      latitude: place.latitude,
      longitude: place.longitude,
      temperature,
      temperature_unit: temperatureUnit,
      wind_speed: windSpeed,
      wind_speed_unit: windSpeedUnit,
      summary: `${locationLabel}: ${temperature}${temperatureUnit}, wind ${windSpeed} ${windSpeedUnit}.`,
    });
  } catch (err) {
    return NextResponse.json(
      { error: "internal", detail: err instanceof Error ? err.message : String(err) },
      { status: 500 },
    );
  }
}
